version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sales_cards
    env_file:
      - .env

  sales_cards:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/sales_cards
    environment:
      POSTGRES_DB: "sales_cards"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

volumes:
  db-data:
  web-data: