version: '3'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - sales_cards
    env_file:
      - .env

  sales_cards:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/sales_cards
    environment:
      - POSTGRES_USER:admin
      - POSTGRES_PASSWORD:admin
    ports:
      - "5432:5432"

volumes:
  db-data:
  web-data: